Update deployment target to iOS12
rechsteiner/Parchment pull request #661
Opened 2023-03-07 06:37 UTC by simorgh3196

Change the deployment target to iOS12 according to the recommended setting.

2023-03-07 19:11 UTC, rechsteiner requested changes

2023-03-07 19:11 UTC, rechsteiner commented on Package.swift
> -    platforms: [.iOS("9.0")],
It looks like Xcode 14 supports iOS 11 and up, so I think we should do the same here. Also, can you update the IPHONEOS_DEPLOYMENT_TARGET build setting for the Parchment target as well?

> The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99.

2023-03-08 03:09 UTC, simorgh3196 commented on Package.swift
> -    platforms: [.iOS("9.0")],
Thanks for the review.
I have fixed it, please check again.

2023-03-09 09:31 UTC, rechsteiner approved these changes

2023-03-09 09:31 UTC, rechsteiner commented on Package.swift
> -    platforms: [.iOS("9.0")],
Looks great! Thanks for fixing 🙌

2023-03-09 09:32 UTC, merged